# Generated by Django 6.0.1 on 2026-01-29 06:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_id', models.CharField(blank=True, editable=False, max_length=25, null=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remaining_balance', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True)),
                ('term', models.IntegerField(choices=[(6, '6 Months'), (9, '9 Months'), (12, '12 Months'), (24, '24 Months')])),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('OVERDUE', 'Overdue')], default='ACTIVE', max_length=10)),
                ('date_issued', models.DateField(auto_now_add=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='users.borrower')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_released', models.DateField(default=django.utils.timezone.now)),
                ('down_payment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit', models.CharField(max_length=255)),
                ('loan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='release_details', to='users.loan')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(blank=True, editable=False, max_length=25, null=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='users.loan')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_type', models.CharField(choices=[('CASH', 'Cash'), ('TRANSFER', 'Bank Transfer'), ('GCASH', 'GCash')], default='CASH', max_length=20)),
                ('month_for', models.DateField()),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.borrower')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.payment')),
            ],
        ),
    ]
