# Generated by Django 6.0.1 on 2026-02-02 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_loanplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='EbikeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('srp', models.DecimalField(decimal_places=2, help_text='Suggested Retail Price', max_digits=12)),
                ('downpayment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('installment_6_months', models.DecimalField(decimal_places=2, max_digits=12)),
                ('installment_12_months', models.DecimalField(decimal_places=2, max_digits=12)),
                ('installment_15_months', models.DecimalField(decimal_places=2, max_digits=12)),
                ('installment_18_months', models.DecimalField(decimal_places=2, max_digits=12)),
                ('installment_24_months', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='LoanPlan',
        ),
        migrations.RemoveField(
            model_name='monthlyrelease',
            name='unit',
        ),
        migrations.AlterField(
            model_name='loan',
            name='term',
            field=models.IntegerField(choices=[(6, '6 Months'), (12, '12 Months'), (15, '15 Months'), (18, '18 Months'), (24, '24 Months')]),
        ),
        migrations.AddField(
            model_name='loan',
            name='ebike_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='users.ebikemodel'),
        ),
    ]
